### ISSUE TITLE
Two controllers

### ISSUE THREAD

**Issue by sanguino** [SukkoPera/PsxControllerShield#1]
This shield is amazing!! Great Job!!

Can I use two shields in the same board? I think not, but because its spi there should be a way to do it
Did you plan to make a two connectors board? Can I help you to make it possible? 

:)

**Comment by SukkoPera** [comment]
Yup, the shield doesn't support it (unless you hack it) but having more than one controller should just be a matter of using a different "Attention" pin for each one (and PsxNewLib supports this already).

I don't plan to make a board with two connectors, but maybe having a few switchable Attention pins would allow stacking more than one. If you want to have a go at this, note that there's already a newer version in the *devel* branch (featuring a second voltage regulator for the motors).
